package selenium_solutions;
//Generated by Selenium IDE
import org.junit.Test;

import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class DefaultSuiteTest {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
 driver = new ChromeDriver();
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
 driver.quit();
}
@Test
public void craftsvilla() {
 // Test name: craftsvilla
 // Step # | name | target | value | comment
 // 1 | open | / |  | 
 driver.get("https://www.craftsvilla.com//");
 // 2 | setWindowSize | 792x824 |  | 
 driver.manage().window().setSize(new Dimension(792, 824));
 // 3 | mouseOver | linkText=SAREES |  | 
 {
   WebElement element = driver.findElement(By.linkText("SAREES"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element).perform();
 }
 // 4 | click | linkText=SAREES |  | 
 driver.findElement(By.linkText("SAREES")).click();
 // 5 | mouseOut | linkText=SAREES |  | 
 {
   WebElement element = driver.findElement(By.tagName("body"));
   Actions builder = new Actions(driver);
   builder.moveToElement(element, 0, 0).perform();
 }
 // 6 | click | linkText=SAREES |  | 
 driver.findElement(By.linkText("SAREES")).click();
 // 7 | click | linkText=SAREES |  | 
 driver.findElement(By.linkText("SAREES")).click();
 // 8 | click | linkText=SAREES |  | 
 driver.findElement(By.linkText("SAREES")).click();
 // 9 | doubleClick | linkText=SAREES |  | 
 {
   WebElement element = driver.findElement(By.linkText("SAREES"));
   Actions builder = new Actions(driver);
   builder.doubleClick(element).perform();
 }
 // 10 | doubleClick | xpath=//div[@id='main']/div[2]/div[2]/div/div/div[2]/a/img |  | 
 {
   WebElement element = driver.findElement(By.xpath("//div[@id=\'main\']/div[2]/div[2]/div/div/div[2]/a/img"));
   Actions builder = new Actions(driver);
   builder.doubleClick(element).perform();
 }
 // 11 | click | css=.col-xs-6:nth-child(1) .product-image > .product-image |  | 
 driver.findElement(By.cssSelector(".col-xs-6:nth-child(1) .product-image > .product-image")).click();
 // 12 | click | id=zoom_1 |  | 
 driver.findElement(By.id("zoom_1")).click();
 // 13 | click | css=#addtocart > span |  | 
 driver.findElement(By.cssSelector("#addtocart > span")).click();
 // 14 | click | css=#size_XXL span |  | 
 driver.findElement(By.cssSelector("#size_XXL span")).click();
 // 15 | click | css=#addtocart > span |  | 
 driver.findElement(By.cssSelector("#addtocart > span")).click();
 // 16 | click | id=remove-item-btn |  | 
 driver.findElement(By.id("remove-item-btn")).click();
 // 17 | click | id=open-remove-item-modal |  | 
 driver.findElement(By.id("open-remove-item-modal")).click();
 // 18 | click | id=remove-item-btn |  | 
 driver.findElement(By.id("remove-item-btn")).click();
}
}



